/* ============================================================
   MATA60 – Banco de Dados
   Projeto Completo – Marco 1 + Marco 2
   Autor: Vinicius Oliveira Caires
   SGBD: PostgreSQL
   Observação:
   - Script AUTOSSUFICIENTE
   - 100% SQL (sem uso de linguagens externas)
   - Pode ser executado do zero em um banco vazio
   ============================================================ */




/* ============================================================
   MARCO 1 – DEFINIÇÃO DO ESQUEMA (DDL)
   ============================================================ */

/* --- Tabelas de domínio --- */

CREATE TABLE tb_tp_categoria_inscricao (
  cd_tp_categoria  VARCHAR(50) PRIMARY KEY,
  ds_tp_categoria  VARCHAR(150) NOT NULL
);

CREATE TABLE tb_st_inscricao (
  cd_st_inscricao  VARCHAR(50) PRIMARY KEY,
  ds_st_inscricao  VARCHAR(150) NOT NULL
);

CREATE TABLE tb_tp_metodo_pagto (
  cd_tp_metodo     VARCHAR(50) PRIMARY KEY,
  ds_tp_metodo     VARCHAR(150) NOT NULL
);

CREATE TABLE tb_tp_certificado (
  cd_tp_certificado VARCHAR(100) PRIMARY KEY,
  ds_tp_certificado VARCHAR(150) NOT NULL
);



/* --- Tabelas principais --- */

CREATE TABLE tb_evento (
  id_evento        INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  no_evento        VARCHAR(200) NOT NULL,
  nu_edicao        VARCHAR(50),
  an_evento        INTEGER NOT NULL,
  no_instituicao   VARCHAR(200)
);

CREATE TABLE tb_participante (
  id_participante  INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  no_participante  VARCHAR(200) NOT NULL,
  ds_email         VARCHAR(200) NOT NULL UNIQUE,
  no_afiliacao     VARCHAR(200),
  tp_participante  VARCHAR(50)
);

CREATE TABLE tb_artigo (
  id_artigo        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  no_titulo        VARCHAR(300) NOT NULL,
  tx_resumo        TEXT,
  no_arquivo       VARCHAR(500),
  no_trilha        VARCHAR(100),
  id_evento        INTEGER NOT NULL,
  CONSTRAINT fk_artigo_evento
    FOREIGN KEY (id_evento)
    REFERENCES tb_evento (id_evento)
);

CREATE TABLE tb_sessao (
  id_sessao        INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id_evento        INTEGER NOT NULL,
  dt_sessao        DATE NOT NULL,
  hr_sessao        TIME NOT NULL,
  no_sala          VARCHAR(100),
  CONSTRAINT fk_sessao_evento
    FOREIGN KEY (id_evento)
    REFERENCES tb_evento (id_evento)
);

CREATE TABLE rl_sessao_artigo (
  id_sessao        INTEGER NOT NULL,
  id_artigo        INTEGER NOT NULL,
  CONSTRAINT pk_rl_sessao_artigo PRIMARY KEY (id_sessao, id_artigo),
  CONSTRAINT fk_rl_sessao
    FOREIGN KEY (id_sessao)
    REFERENCES tb_sessao (id_sessao),
  CONSTRAINT fk_rl_artigo
    FOREIGN KEY (id_artigo)
    REFERENCES tb_artigo (id_artigo)
);

CREATE TABLE tb_inscricao (
  id_inscricao     INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id_participante  INTEGER NOT NULL,
  id_evento        INTEGER NOT NULL,
  tp_categoria     VARCHAR(50),
  st_status        VARCHAR(50),
  CONSTRAINT fk_insc_participante
    FOREIGN KEY (id_participante)
    REFERENCES tb_participante (id_participante),
  CONSTRAINT fk_insc_evento
    FOREIGN KEY (id_evento)
    REFERENCES tb_evento (id_evento),
  CONSTRAINT uk_inscricao
    UNIQUE (id_participante, id_evento),
  CONSTRAINT fk_insc_categoria
    FOREIGN KEY (tp_categoria)
    REFERENCES tb_tp_categoria_inscricao (cd_tp_categoria),
  CONSTRAINT fk_insc_status
    FOREIGN KEY (st_status)
    REFERENCES tb_st_inscricao (cd_st_inscricao)
);

CREATE TABLE tb_pagamento (
  id_pagamento     INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id_inscricao     INTEGER NOT NULL,
  vl_pagamento     NUMERIC(10,2) NOT NULL,
  dt_pagamento     DATE NOT NULL,
  tp_metodo        VARCHAR(50),
  CONSTRAINT fk_pgto_inscricao
    FOREIGN KEY (id_inscricao)
    REFERENCES tb_inscricao (id_inscricao),
  CONSTRAINT fk_pgto_metodo
    FOREIGN KEY (tp_metodo)
    REFERENCES tb_tp_metodo_pagto (cd_tp_metodo)
);

CREATE TABLE tb_certificado (
  id_certificado   INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id_participante  INTEGER NOT NULL,
  id_evento        INTEGER NOT NULL,
  tp_certificado   VARCHAR(100) NOT NULL,
  dt_emissao       DATE NOT NULL,
  CONSTRAINT fk_cert_participante
    FOREIGN KEY (id_participante)
    REFERENCES tb_participante (id_participante),
  CONSTRAINT fk_cert_evento
    FOREIGN KEY (id_evento)
    REFERENCES tb_evento (id_evento),
  CONSTRAINT fk_cert_tipo
    FOREIGN KEY (tp_certificado)
    REFERENCES tb_tp_certificado (cd_tp_certificado)
);

CREATE TABLE tb_revisor (
  id_revisor       INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id_participante  INTEGER NOT NULL UNIQUE,
  CONSTRAINT fk_revisor_participante
    FOREIGN KEY (id_participante)
    REFERENCES tb_participante (id_participante)
);

CREATE TABLE tb_revisao (
  id_revisao       INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id_artigo        INTEGER NOT NULL,
  id_revisor       INTEGER NOT NULL,
  ds_parecer       TEXT,
  nu_nota          NUMERIC(3,1),
  nu_versao        INTEGER,
  dt_revisao       DATE,
  CONSTRAINT fk_rev_artigo
    FOREIGN KEY (id_artigo)
    REFERENCES tb_artigo (id_artigo),
  CONSTRAINT fk_rev_revisor
    FOREIGN KEY (id_revisor)
    REFERENCES tb_revisor (id_revisor),
  CONSTRAINT ck_rev_nota_range
    CHECK (nu_nota IS NULL OR (nu_nota >= 0.0 AND nu_nota <= 10.0)),
  CONSTRAINT uk_rev_art_revisor_versao
    UNIQUE (id_artigo, id_revisor, nu_versao)
);




/* ============================================================
   MARCO 1 – POPULAÇÃO DO BANCO (DML)
   ============================================================ */

INSERT INTO tb_tp_categoria_inscricao VALUES
 ('ESTUDANTE','Inscrição de estudante'),
 ('PROFISSIONAL','Inscrição profissional'),
 ('CONVIDADO','Isento/Convidado');

INSERT INTO tb_st_inscricao VALUES
 ('PENDENTE','Aguardando pagamento'),
 ('PAGO','Pago e confirmado'),
 ('CANCELADO','Inscrição cancelada');

INSERT INTO tb_tp_metodo_pagto VALUES
 ('PIX','Pagamento via PIX'),
 ('CARTAO','Cartão de crédito'),
 ('BOLETO','Boleto bancário');

INSERT INTO tb_tp_certificado VALUES
 ('PARTICIPACAO','Certificado de participação'),
 ('APRESENTACAO','Certificado de apresentação'),
 ('REVISAO','Certificado de revisão');

INSERT INTO tb_evento (no_evento, an_evento, no_instituicao) VALUES
 ('Congresso de Pesquisa Acadêmica', 2025, 'Salvador - BA'),
 ('Seminário de Iniciação Científica', 2025, 'Feira de Santana - BA');

INSERT INTO tb_participante (no_participante, ds_email, no_afiliacao)
SELECT
  'Participante ' || g,
  'p' || g || '@email.com',
  'Instituição ' || (g % 10)
FROM generate_series(1,5000) g;

INSERT INTO tb_revisor (id_participante)
SELECT id_participante
FROM tb_participante
WHERE id_participante <= 1500;

INSERT INTO tb_artigo (no_titulo, no_trilha, tx_resumo, id_evento)
SELECT
  'Artigo ' || id_participante,
  'Sistemas',
  'Resumo sintético',
  1
FROM tb_participante
WHERE id_participante <= 3000;

INSERT INTO tb_sessao (id_evento, dt_sessao, hr_sessao, no_sala) VALUES
 (1, DATE '2025-09-10', TIME '10:00', 'Auditório 1'),
 (1, DATE '2025-09-10', TIME '14:00', 'Sala 101'),
 (2, DATE '2025-11-20', TIME '09:00', 'Auditório 2');

INSERT INTO rl_sessao_artigo (id_sessao, id_artigo)
SELECT s.id_sessao, a.id_artigo
FROM tb_sessao s
JOIN tb_artigo a ON a.id_artigo <= 50;

INSERT INTO tb_inscricao (id_participante, id_evento, tp_categoria, st_status)
SELECT
  id_participante,
  1,
  'ESTUDANTE',
  CASE WHEN id_participante % 2 = 0 THEN 'PAGO' ELSE 'PENDENTE' END
FROM tb_participante
WHERE id_participante <= 5000;

INSERT INTO tb_pagamento (id_inscricao, vl_pagamento, dt_pagamento, tp_metodo)
SELECT
  id_inscricao,
  150.00,
  DATE '2025-08-15',
  'PIX'
FROM tb_inscricao
WHERE st_status = 'PAGO';

INSERT INTO tb_certificado (id_participante, id_evento, tp_certificado, dt_emissao)
SELECT
  id_participante,
  1,
  'PARTICIPACAO',
  DATE '2025-09-12'
FROM tb_participante
WHERE id_participante <= 5000;

INSERT INTO tb_revisao (id_artigo, id_revisor, ds_parecer, nu_nota, nu_versao, dt_revisao)
SELECT
  a.id_artigo,
  r.id_revisor,
  'Parecer padrão',
  8.0,
  1,
  DATE '2025-08-20'
FROM tb_artigo a
JOIN tb_revisor r ON r.id_revisor <= 10
WHERE a.id_artigo <= 100;




/* ============================================================
   MARCO 2 – ROTINAS AVANÇADAS (MV, SP, TRANSAÇÕES)
   ============================================================ */

/* --- Materialized Views --- */

DROP MATERIALIZED VIEW IF EXISTS mv_inscricao_evento_status;
CREATE MATERIALIZED VIEW mv_inscricao_evento_status AS
SELECT id_evento, id_participante, st_status, COUNT(*) qt_inscricoes
FROM tb_inscricao
GROUP BY id_evento, id_participante, st_status;

DROP MATERIALIZED VIEW IF EXISTS mv_artigos_evento_trilha;
CREATE MATERIALIZED VIEW mv_artigos_evento_trilha AS
SELECT id_evento, no_trilha, COUNT(*) qt_artigos
FROM tb_artigo
GROUP BY id_evento, no_trilha;

DROP MATERIALIZED VIEW IF EXISTS mv_evento_financeiro;
CREATE MATERIALIZED VIEW mv_evento_financeiro AS
SELECT
  e.id_evento, e.no_evento,
  COUNT(i.id_inscricao) qt_inscricoes,
  COALESCE(SUM(p.vl_pagamento),0) vl_total_arrecadado
FROM tb_evento e
LEFT JOIN tb_inscricao i ON i.id_evento = e.id_evento
LEFT JOIN tb_pagamento p ON p.id_inscricao = i.id_inscricao
GROUP BY e.id_evento, e.no_evento;

DROP MATERIALIZED VIEW IF EXISTS mv_desempenho_trilha;
CREATE MATERIALIZED VIEW mv_desempenho_trilha AS
SELECT
  a.no_trilha,
  COUNT(r.id_revisao) qt_revisoes,
  AVG(r.nu_nota)::NUMERIC(4,2) media_notas
FROM tb_artigo a
JOIN tb_revisao r ON r.id_artigo = a.id_artigo
GROUP BY a.no_trilha;

DROP MATERIALIZED VIEW IF EXISTS mv_dashboard_operacional_intermediario;
CREATE MATERIALIZED VIEW mv_dashboard_operacional_intermediario AS
SELECT
  e.id_evento, e.no_evento, i.st_status,
  COUNT(i.id_inscricao) qt_inscricoes
FROM tb_evento e
JOIN tb_inscricao i ON i.id_evento = e.id_evento
JOIN tb_participante p ON p.id_participante = i.id_participante
GROUP BY e.id_evento, e.no_evento, i.st_status;

DROP MATERIALIZED VIEW IF EXISTS mv_dashboard_operacional_avancado;
CREATE MATERIALIZED VIEW mv_dashboard_operacional_avancado AS
SELECT
  e.id_evento, e.no_evento,
  COUNT(DISTINCT a.id_artigo) qt_artigos,
  (
    SELECT COUNT(*)
    FROM tb_revisao r
    JOIN tb_artigo a2 ON a2.id_artigo = r.id_artigo
    WHERE a2.id_evento = e.id_evento
  ) qt_revisoes
FROM tb_evento e
JOIN tb_artigo a ON a.id_evento = e.id_evento
WHERE EXISTS (
  SELECT 1 FROM tb_sessao s WHERE s.id_evento = e.id_evento
)
GROUP BY e.id_evento, e.no_evento;


/* --- Stored Procedures --- */

CREATE OR REPLACE PROCEDURE sp_cadastro_inscricao(
  p_id_participante INTEGER,
  p_id_evento INTEGER,
  p_categoria TEXT,
  p_status TEXT
)
LANGUAGE SQL
AS $$
  INSERT INTO tb_inscricao (id_participante, id_evento, tp_categoria, st_status)
  SELECT p_id_participante, p_id_evento, p_categoria, 'PENDENTE'
  WHERE NOT EXISTS (
    SELECT 1 FROM tb_inscricao
    WHERE id_participante = p_id_participante
      AND id_evento = p_id_evento
  );

  UPDATE tb_inscricao
  SET tp_categoria = p_categoria,
      st_status = p_status
  WHERE id_participante = p_id_participante
    AND id_evento = p_id_evento;
$$;

CREATE OR REPLACE PROCEDURE sp_manter_artigo(
  p_id_artigo INTEGER,
  p_titulo TEXT,
  p_trilha TEXT,
  p_id_evento INTEGER
)
LANGUAGE SQL
AS $$
  INSERT INTO tb_artigo (id_artigo, no_titulo, no_trilha, id_evento)
  SELECT p_id_artigo, p_titulo, p_trilha, p_id_evento
  WHERE NOT EXISTS (SELECT 1 FROM tb_artigo WHERE id_artigo = p_id_artigo);

  UPDATE tb_artigo
  SET no_titulo = p_titulo,
      no_trilha = p_trilha
  WHERE id_artigo = p_id_artigo;
$$;

CREATE OR REPLACE PROCEDURE sp_refresh_dashboard_estrategico()
LANGUAGE SQL
AS $$
  REFRESH MATERIALIZED VIEW mv_evento_financeiro;
  REFRESH MATERIALIZED VIEW mv_desempenho_trilha;
$$;

CREATE OR REPLACE PROCEDURE sp_refresh_dashboard_operacional()
LANGUAGE SQL
AS $$
  REFRESH MATERIALIZED VIEW mv_dashboard_operacional_intermediario;
  REFRESH MATERIALIZED VIEW mv_dashboard_operacional_avancado;
$$;




/* ============================================================
   FIM DO SCRIPT
   ============================================================ */
